version: '3'
services:

  nginx:
    depends_on:
       - odfe-node1
       - kibana
    image: nginx:1.13.3
    container_name: nginx
    volumes:
      - nginx-sites:/etc/nginx/conf.d
    ports:
      - 81:81
      - 82:82

  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.4.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1
      
      - node.master=true
      - node.data=true
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - network.host=0.0.0.0
      
      - cluster.initial_master_nodes=odfe-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
      
  kibana:
    depends_on:
       - odfe-node1
    image: amazon/opendistro-for-elasticsearch-kibana:1.4.0
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
  
volumes:
  odfe-data1: {}
  nginx-sites:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./nginx/sites-enabled
